# 1.Print 'Hello HCIA'.
Печать "Hello HCIA"

In [1]:
print('Hello HCIA')

Hello HCIA


# 2.Define two variables and calculate their sum.
Определите две переменные и вычислите их сумму

In [165]:
a=int(input())
b=int(input())
print(a+b)

12
12
24


# 3.Define a list and replicate in three different ways.
Составьте список и воспроизведите его тремя разными способами.

In [17]:
x=['H','e','l','l','o',_,'H','C','I','A']

In [18]:
print(x)

['H', 'e', 'l', 'l', 'o', '', 'H', 'C', 'I', 'A']


In [23]:
for a in range(len(x)):
    print(x[a])

H
e
l
l
o

H
C
I
A


In [22]:
for a in range(len(x)):
    print(x[a], end=' ') #(end=' ')-что бы не пеескакивало на новую строчку

H e l l o  H C I A 

# 4.Define two lists and merge them together.
Определите два списка и объедините их вместе.

In [28]:
a=['H','e','l','l','o']
b=['H','C','I','A','!!!!!']
print(a+b)

['H', 'e', 'l', 'l', 'o', 'H', 'C', 'I', 'A', '!!!!!']


# 5. Get the last element of the list and print it.
Возьмите последний элемент списка и распечатайте его.

In [33]:
b=['H','C','I','A','!!!!!']
b[-1]

'!!!!!'

# 6.Define a tuple that contains only one element.
Определите кортеж, содержащий только один элемент.

In [38]:
c=('Y')
print(c)

Y


# 7.Define a three-line long string.
Определите длинную строку из трех строк.

In [1]:
list1=['motor', 'gearbox', 'drive', 'differential']
list2=['valves', 'entered', 'the', 'piston']
list3=['bumper', 'hood', 'headlight', 'fender', 'door']
##используем len(). 
##Она посчитает количество символов в строке каждого элемента списка строк,функция max() выберет максимальное число
list_all=[list1,list2,list3]
max(list_all, key=len)

['bumper', 'hood', 'headlight', 'fender', 'door']

# 8.Define a tuple and then use the 'for loop' to print all the elements.
Определите кортеж, а затем используйте цикл for для печати всех элементов.

In [87]:
a=('H','e','l','l','o')
for i in a[0:5]:
    print(i)
print(a)

H
e
l
l
o
('H', 'e', 'l', 'l', 'o')


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.
Определите функцию для умножения, например Mul(8,6),и ее выход 48

In [95]:
def Mul(x,y):
    return x*y

print(Mul(8,6))

48


# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.
Импортируйте numpy и используйте numpy для определения массива, его форма - (5,5), а все его элементы - 0.

In [65]:
import numpy as np 

a=np.zeros((5,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.
Импортируйте numpy и используйте numpy для определения массива, форма - (4,6), а все элементы - 0.

In [2]:
import numpy as np 

a=np.zeros((4,6))
print(a)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).
Используйте numpy.arrange () для создания массива формы (15,), затем измените форму на (3,5).

In [122]:
a=np.arange(15)
print(a.shape)
print(a.reshape(3, 5))

(15,)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


# 13.Define two matrices, then calculate and print the result of their point multiplication.
Определите две матрицы, затем вычислите и распечатайте результат умножения их точек.

In [3]:
a=np.arange(10).reshape(2,5)
b=np.arange(10).reshape(2,5)
print (a*b)

[[ 0  1  4  9 16]
 [25 36 49 64 81]]
